name: Fast RDP (IN)

on:
  workflow_dispatch:

jobs:
  fast-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure RDP
        run: |
          # Enable RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Create User
        run: |
          $password = -join ((33..126) | Get-Random -Count 16 | ForEach-Object { [char]$_ })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDPUser" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Setup Ngrok (Fast TCP Tunnel)
        run: |
          # Download ngrok
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "$env:TEMP\ngrok.zip"
          Expand-Archive -Path "$env:TEMP\ngrok.zip" -DestinationPath "$env:TEMP\ngrok" -Force
          
          # Start ngrok tunnel with your token
          Start-Process -FilePath "$env:TEMP\ngrok\ngrok.exe" -ArgumentList "tcp", "3389", "--authtoken", "${{ secrets.NGROK_AUTH_TOKEN }}", "--region", "in" -WindowStyle Hidden
          Start-Sleep -Seconds 3
          
          # Get the public URL
          $tunnelInfo = (Invoke-WebRequest -Uri "http://localhost:4040/api/tunnels" -UseBasicParsing).Content | ConvertFrom-Json
          $publicUrl = $tunnelInfo.tunnels[0].public_url
          $rdpAddress = $publicUrl -replace "tcp://", "" -replace ":\d+", ""
          $rdpPort = $publicUrl -replace ".*:", ""
          
          echo "RDP_ADDRESS=$rdpAddress" >> $env:GITHUB_ENV
          echo "RDP_PORT=$rdpPort" >> $env:GITHUB_ENV
          Write-Host "Ngrok Tunnel Established: $publicUrl"

      - name: Display Connection Info
        run: |
          Write-Host "`n🎯 **ULTRA-FAST RDP CONNECTION**"
          Write-Host "=========================================="
          Write-Host "Address: $env:RDP_ADDRESS"
          Write-Host "Port: $env:RDP_PORT"
          Write-Host "Username: RDPUser"
          Write-Host "Password: $env:RDP_PASSWORD"
          Write-Host "=========================================="
          Write-Host "`nIn Remote Desktop Connection:"
          Write-Host "Computer: $env:RDP_ADDRESS:$env:RDP_PORT"
          Write-Host "==========================================`n"

      - name: Maintain Connection
        run: |
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Ready - Connect to: $env:RDP_ADDRESS:$env:RDP_PORT"
              Start-Sleep -Seconds 60
          }